name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.4.1
      with:
          arch: amd64

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{github.workspace}}/qt/'
        install-deps: 'true'

    - name: Configure CMake
      run: cd Application && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{env.Qt6_Dir}}/lib/cmake/" -DQt6_DIR=${{env.Qt6_Dir}}/lib/cmake/Qt6/ -GNinja -DCMAKE_MAKE_PROGRAM=ninja -B '${{github.workspace}}/../build'

    - name: Build
      run: cd Application && cmake --build '${{github.workspace}}'/build --target all
